<?php

namespace Database\Seeders;

use App\Models\Alphabet;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AlphabetTableSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $alphabet = [
            ["Hiragana"=>"あ","Katakana"=>"ア","Romanji"=>"a"],
            ["Hiragana"=>"い","Katakana"=>"イ","Romanji"=>"i"],
            ["Hiragana"=>"う","Katakana"=>"ウ","Romanji"=>"u"],
            ["Hiragana"=>"え","Katakana"=>"エ","Romanji"=>"e"],
            ["Hiragana"=>"お","Katakana"=>"オ","Romanji"=>"o"],
            ["Hiragana"=>"か","Katakana"=>"カ","Romanji"=>"ka"],
            ["Hiragana"=>"き","Katakana"=>"き","Romanji"=>"ki"],
            ["Hiragana"=>"く","Katakana"=>"ク","Romanji"=>"ku"],
            ["Hiragana"=>"け","Katakana"=>"ケ","Romanji"=>"ke"],
            ["Hiragana"=>"こ","Katakana"=>"コ","Romanji"=>"ko"],
            ["Hiragana"=>"さ","Katakana"=>"サ","Romanji"=>"sa"],
            ["Hiragana"=>"し","Katakana"=>"シ","Romanji"=>"shi"],
            ["Hiragana"=>"す","Katakana"=>"ス","Romanji"=>"su"],
            ["Hiragana"=>"せ","Katakana"=>"セ","Romanji"=>"se"],
            ["Hiragana"=>"そ","Katakana"=>"ソ","Romanji"=>"so"],
            ["Hiragana"=>"た","Katakana"=>"タ","Romanji"=>"ta"],
            ["Hiragana"=>"ち","Katakana"=>"千","Romanji"=>"chi"],
            ["Hiragana"=>"つ","Katakana"=>"ツ","Romanji"=>"stu"],
            ["Hiragana"=>"て","Katakana"=>"テ","Romanji"=>"te"],
            ["Hiragana"=>"と","Katakana"=>"ト","Romanji"=>"to"],
            ["Hiragana"=>"な","Katakana"=>"ナ","Romanji"=>"na"],
            ["Hiragana"=>"に","Katakana"=>"二","Romanji"=>"ni"],
            ["Hiragana"=>"ぬ","Katakana"=>"ヌ","Romanji"=>"nu"],
            ["Hiragana"=>"ね","Katakana"=>"ネ","Romanji"=>"ne"],
            ["Hiragana"=>"の","Katakana"=>"ノ","Romanji"=>"no"],
            ["Hiragana"=>"は","Katakana"=>"ハ","Romanji"=>"Ha"],
            ["Hiragana"=>"ひ","Katakana"=>"ヒ","Romanji"=>"Hi"],
            ["Hiragana"=>"ふ","Katakana"=>"フ","Romanji"=>"fu"],
            ["Hiragana"=>"へ","Katakana"=>"ㇸ","Romanji"=>"He"],
            ["Hiragana"=>"ほ","Katakana"=>"ホ","Romanji"=>"Ho"],
            ["Hiragana"=>"ま","Katakana"=>"マ","Romanji"=>"ma"],
            ["Hiragana"=>"み","Katakana"=>"ミ","Romanji"=>"mi"],
            ["Hiragana"=>"む","Katakana"=>"ム","Romanji"=>"mu"],
            ["Hiragana"=>"め","Katakana"=>"メ","Romanji"=>"me"],
            ["Hiragana"=>"も","Katakana"=>"モ","Romanji"=>"mo"],
            ["Hiragana"=>"や","Katakana"=>"ヤ","Romanji"=>"ya"],
            ["Hiragana"=>"ゆ","Katakana"=>"ユ","Romanji"=>"yu"],
            ["Hiragana"=>"よ","Katakana"=>"ヨ","Romanji"=>"yo"],
            ["Hiragana"=>"ら","Katakana"=>"ラ","Romanji"=>"Ra"],
            ["Hiragana"=>"り","Katakana"=>"リ","Romanji"=>"Ri"],
            ["Hiragana"=>"る","Katakana"=>"ル","Romanji"=>"Ru"],
            ["Hiragana"=>"れ","Katakana"=>"レ","Romanji"=>"Re"],
            ["Hiragana"=>"ろ","Katakana"=>"ロ","Romanji"=>"Ro"],
            ["Hiragana"=>"わ","Katakana"=>"ワ","Romanji"=>"wa"],
            ["Hiragana"=>"を","Katakana"=>"","Romanji"=>"o"],
            ["Hiragana"=>"ん","Katakana"=>"ン","Romanji"=>"n"],
            ["Hiragana"=>"が","Katakana"=>"ガ","Romanji"=>"ga"],
            ["Hiragana"=>"ぎ","Katakana"=>"ギ","Romanji"=>"gi"],
            ["Hiragana"=>"ぐ","Katakana"=>"グ","Romanji"=>"gu"],
            ["Hiragana"=>"げ","Katakana"=>"ゲ","Romanji"=>"ge"],
            ["Hiragana"=>"ご","Katakana"=>"ゴ","Romanji"=>"go"],
            ["Hiragana"=>"ざ","Katakana"=>"ザ","Romanji"=>"za"],
            ["Hiragana"=>"じ","Katakana"=>"ジ","Romanji"=>"ji"],
            ["Hiragana"=>"ず","Katakana"=>"ズ","Romanji"=>"zu"],
            ["Hiragana"=>"ぜ","Katakana"=>"ゼ","Romanji"=>"ze"],
            ["Hiragana"=>"ぞ","Katakana"=>"ゾ","Romanji"=>"zo"],
            ["Hiragana"=>"だ","Katakana"=>"ダ","Romanji"=>"da"],
            ["Hiragana"=>"ぢ","Katakana"=>"ヂ","Romanji"=>"ji"],
            ["Hiragana"=>"づ","Katakana"=>"ヅ","Romanji"=>"zu"],
            ["Hiragana"=>"で","Katakana"=>"デ","Romanji"=>"de"],
            ["Hiragana"=>"ど","Katakana"=>"ド","Romanji"=>"do"],
            ["Hiragana"=>"ば","Katakana"=>"バ","Romanji"=>"ba"],
            ["Hiragana"=>"び","Katakana"=>"ビ","Romanji"=>"bi"],
            ["Hiragana"=>"ぶ","Katakana"=>"ブ","Romanji"=>"bu"],
            ["Hiragana"=>"べ","Katakana"=>"ベ","Romanji"=>"be"],
            ["Hiragana"=>"ぼ","Katakana"=>"ボ","Romanji"=>"bo"],
            ["Hiragana"=>"ぱ","Katakana"=>"パ","Romanji"=>"pa"],
            ["Hiragana"=>"ぴ","Katakana"=>"ピ","Romanji"=>"pi"],
            ["Hiragana"=>"ぷ","Katakana"=>"プ","Romanji"=>"pu"],
            ["Hiragana"=>"ぺ","Katakana"=>"ペ","Romanji"=>"pe"],
            ["Hiragana"=>"ぽ","Katakana"=>"ポ","Romanji"=>"po"],
            ["Hiragana"=>"きゃ","Katakana"=>"キャ","Romanji"=>"kya"],
            ["Hiragana"=>"きゅ","Katakana"=>"キュ","Romanji"=>"kyu"],
            ["Hiragana"=>"きょ","Katakana"=>"キョ","Romanji"=>"kyo"],
            ["Hiragana"=>"しゃ","Katakana"=>"シャ","Romanji"=>"sha"],
            ["Hiragana"=>"しゅ","Katakana"=>"シュ","Romanji"=>"shu"],
            ["Hiragana"=>"しょ","Katakana"=>"ショ","Romanji"=>"sho"],
            ["Hiragana"=>"ちゃ","Katakana"=>"チャ","Romanji"=>"cha"],
            ["Hiragana"=>"ちゅ","Katakana"=>"チュ","Romanji"=>"chu"],
            ["Hiragana"=>"ちょ","Katakana"=>"ちょ","Romanji"=>"cho"],
            ["Hiragana"=>"にゃ","Katakana"=>"にゃ","Romanji"=>"nya"],
            ["Hiragana"=>"にゅ","Katakana"=>"にゅ","Romanji"=>"nyu"],
            ["Hiragana"=>"にょ","Katakana"=>"にょ","Romanji"=>"nyo"],
            ["Hiragana"=>"ひゃ","Katakana"=>"ひゃ","Romanji"=>"Hya"],
            ["Hiragana"=>"ひゅ","Katakana"=>"ひゅ","Romanji"=>"Hyu"],
            ["Hiragana"=>"ひょ","Katakana"=>"ひょ","Romanji"=>"Hyo"],
            ["Hiragana"=>"みゃ","Katakana"=>"みゃ","Romanji"=>"mya"],
            ["Hiragana"=>"みゅ","Katakana"=>"みゅ","Romanji"=>"myu"],
            ["Hiragana"=>"みょ","Katakana"=>"みょ","Romanji"=>"myo"],
            ["Hiragana"=>"りゃ","Katakana"=>"りゃ","Romanji"=>"Rya"],
            ["Hiragana"=>"りゅ","Katakana"=>"りゅ","Romanji"=>"Ryu"],
            ["Hiragana"=>"りょ","Katakana"=>"りょ","Romanji"=>"Ryo"],
            ["Hiragana"=>"ぎゃ","Katakana"=>"ぎゃ","Romanji"=>"gya"],
            ["Hiragana"=>"ぎゅ","Katakana"=>"ぎゅ","Romanji"=>"gyu"],
            ["Hiragana"=>"ぎょ","Katakana"=>"ぎょ","Romanji"=>"gyo"],
            ["Hiragana"=>"じゃ","Katakana"=>"じゃ","Romanji"=>"ja"],
            ["Hiragana"=>"じゅ","Katakana"=>"じゅ","Romanji"=>"ju"],
            ["Hiragana"=>"じょ","Katakana"=>"じょ","Romanji"=>"jo"],
            ["Hiragana"=>"びゃ","Katakana"=>"びゃ","Romanji"=>"bya"],
            ["Hiragana"=>"びゅ","Katakana"=>"びゅ","Romanji"=>"byu"],
            ["Hiragana"=>"びょ","Katakana"=>"びょ","Romanji"=>"byo"],
            ["Hiragana"=>"ぴゃ","Katakana"=>"ぴゃ","Romanji"=>"pya"],
            ["Hiragana"=>"ぴゅ","Katakana"=>"ぴゅ","Romanji"=>"pyu"],
            ["Hiragana"=>"ぴょ","Katakana"=>"ぴょ","Romanji"=>"pyo"],
        ];
        foreach($alphabet as $value)
        {
           Alphabet::create($value); 
        }
    }
}
